"""add censored_storage_path to files

Revision ID: 3cdc648c1ee5
Revises: a7768827fca4
Create Date: 2026-08-08 11:30:43.280914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdc648c1ee5'
down_revision = 'a7768827fca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('censored_storage_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'censored_storage_path')
    # ### end Alembic commands ###